const { isBoolean, required } = require("../helpers/inputValidation")
module.exports.createCompositionSchemaValidation = {
  Goalkeaper_No: isBoolean("دربازه بان", "body"),
  Defender_Left: isBoolean("مدافع سمت چپ", "body"),
  Defender_One: isBoolean("مدافع وسط 1", "body"),
  Defender_Two: isBoolean("مدافع وسط 2", "body"),
  Defender_Three: isBoolean("مدافع وسط 3", "body"),
  Defender_Right: isBoolean("مدافع سمت راست", "body"),
  Midfielder_Left: isBoolean("هافبک سمت چپ", "body"),
  Midfielder_One: isBoolean("هافبک وسط 1", "body"),
  Midfielder_Two: isBoolean("هافبک وسط 2", "body"),
  Midfielder_Three: isBoolean("هافبک وسط 3", "body"),
  Midfielder_Right: isBoolean("هافبک سمت راست", "body"),
  Attacker_Left: isBoolean("مهاجم سمت راست", "body"),
  Attacker_One: isBoolean("مهاجم وسط 1", "body"),
  Attacker_Two: isBoolean("مهاجم وسط 2", "body"),
  Attacker_Three: isBoolean("مهاجم وسط 3", "body"),
  Attacker_Right: isBoolean("مهاجم سمت راست", "body"),
  score: isBoolean("امتیاز ترکیب"),
}
