const { isBoolean, required } = require("../helpers/inputValidation")
module.exports.createCompositionSchemaValidation = {
  GOALKEAPER_NO: isBoolean("دربازه بان", "body"),
  DEFENDER_LEFT: isBoolean("مدافع سمت چپ", "body"),
  DEFENDER_ONE: isBoolean("مدافع وسط 1", "body"),
  DEFENDER_TWO: isBoolean("مدافع وسط 2", "body"),
  DEFENDER_THREE: isBoolean("مدافع وسط 3", "body"),
  DEFENDER_RIGHT: isBoolean("مدافع سمت راست", "body"),
  MIDFIELDER_LEFT: isBoolean("هافبک سمت چپ", "body"),
  MIDFIELDER_ONE: isBoolean("هافبک وسط 1", "body"),
  MIDFIELDER_TWO: isBoolean("هافبک وسط 2", "body"),
  MIDFIELDER_THREE: isBoolean("هافبک وسط 3", "body"),
  MIDFIELDER_RIGHT: isBoolean("هافبک سمت راست", "body"),
  ATTACKER_LEFT: isBoolean("مهاجم سمت راست", "body"),
  ATTACKER_ONE: isBoolean("مهاجم وسط 1", "body"),
  ATTACKER_TWO: isBoolean("مهاجم وسط 2", "body"),
  ATTACKER_THREE: isBoolean("مهاجم وسط 3", "body"),
  ATTACKER_RIGHT: isBoolean("مهاجم سمت راست", "body"),
  score: isBoolean("امتیاز ترکیب"),
}
